### ISSUE TITLE
Error during run

### ISSUE THREAD

**Issue by kokyriakidis** [jumphone/SPRINT#28]
I am trying to run SPRINT but I get errors regarding file paths
```
[E::hts_open_format] Failed to open file "/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome_mskTC/all.bam" : No such file or directory
samtools view: failed to open "/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome_mskTC/all.bam" for reading: No such file or directory
cp: cannot stat '/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome_mskTC/./all.sam': No such file or directory
[E::hts_open_format] Failed to open file "/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome_mskTC/all.bam" : No such file or directory
samtools view: failed to open "/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome_mskTC/all.bam" for reading: No such file or directory
Traceback (most recent call last):
  File "run.py", line 7, in <module>
  File "sprint/pipeline.py", line 42, in pipeline
  File "sprint/sprint_main.py", line 476, in main
  File "sprint/tools_sam/recover_sam.py", line 39, in recover_sam
IOError: [Errno 2] No such file or directory: '/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp/genome_mskAG_all.sam'
Failed to execute script run

```

I do not understand why it adds "/" before and after "tmp". Do you have a solution to this situation?

The command I used is:
```
/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/SPRINT/bin/sprint main \
-1 /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/input/SRR609422_1.fastq \
-2 /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/input/SRR609422_2.fastq \
-rp /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/SPRINT/dbrep/hg19_repeat.txt \
-c 6 \
-p 20 \
/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/hg19/hg19.fa \
AD1E \
/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/bwa-0.7.17/bwa \
/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/samtools-1.13/samtools
```

**Comment by jumphone** [comment]
SPRINT will generate a "tmp" folder to store some files when processing sequencing data. 

Please attach the full error log.

**Comment by jumphone** [comment]
SPRINT will generate a "tmp" folder to store some files when processing sequencing data. 

Please attach the full error log.

**Comment by jumphone** [comment]
We have tested sprint in multiple servers, and the "/" will not cause error.

**Comment by kokyriakidis** [comment]
```
[bwa_aln_core] refine gapped alignments... 0.44 sec
[bwa_aln_core] print alignments... 0.12 sec
[bwa_aln_core] 21939744 sequences have been processed.
[main] Version: 0.7.17-r1188
[main] CMD: /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/bwa-0.7.17/bwa samse -n4 /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/hg19/hg19.fa /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome/read2.sai /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp/cut_read2.fastq
[main] Real time: 311.477 sec; CPU: 308.874 sec
[main] Version: 0.7.17-r1188
[main] CMD: /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/bwa-0.7.17/bwa samse -n4 /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/hg19/hg19.fa /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome/read1.sai /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp/cut_read1.fastq
[main] Real time: 312.621 sec; CPU: 310.092 sec
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -u         Output uncompressed data (equivalent to -l 0)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -M         Use minimiser for clustering unaligned/unplaced reads
  -K INT     Kmer size to use for minimiser [20]
  -n         Sort by read name (not compatible with samtools index command)
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
  --no-PG    do not add a PG line
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
      --write-index
               Automatically index the output files [off]
      --verbosity INT
               Set level of verbosity
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -u         Output uncompressed data (equivalent to -l 0)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -M         Use minimiser for clustering unaligned/unplaced reads
  -K INT     Kmer size to use for minimiser [20]
  -n         Sort by read name (not compatible with samtools index command)
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
  --no-PG    do not add a PG line
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
      --write-index
               Automatically index the output files [off]
      --verbosity INT
               Set level of verbosity
sh: 0: getcwd() failed: No such file or directory
[E::hts_open_format] Failed to open file "/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome/name_read1_sorted.bam" : No such file or directory
samtools merge: fail to open "/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome/name_read1_sorted.bam": No such file or directory
sh: 0: getcwd() failed: No such file or directory
[E::hts_open_format] Failed to open file "/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome/all.bam" : No such file or directory
samtools view: failed to open "/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome/all.bam" for reading: No such file or directory
sh: 0: getcwd() failed: No such file or directory
cp: cannot stat '/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome/./all.sam': No such file or directory
sh: 0: getcwd() failed: No such file or directory
[E::hts_open_format] Failed to open file "/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome/all.bam" : No such file or directory
samtools view: failed to open "/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome/all.bam" for reading: No such file or directory
sh: 0: getcwd() failed: No such file or directory
[bwa_aln] 17bp reads: max_diff = 2
[bwa_aln] 38bp reads: max_diff = 3
[bwa_aln] 64bp reads: max_diff = 4
[bwa_aln] 93bp reads: max_diff = 5
[bwa_aln] 124bp reads: max_diff = 6
[bwa_aln] 157bp reads: max_diff = 7
[bwa_aln] 190bp reads: max_diff = 8
[bwa_aln] 225bp reads: max_diff = 9
[main] Version: 0.7.17-r1188
[main] CMD: /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/bwa-0.7.17/bwa aln -t 20 /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/hg19/hg19.fa.mskAG.fa /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//regular_unmapped_A_to_G.fq
[main] Real time: 1.459 sec; CPU: 1.438 sec
sh: 0: getcwd() failed: No such file or directory
[main] Version: 0.7.17-r1188
[main] CMD: /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/bwa-0.7.17/bwa samse -n4 /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/hg19/hg19.fa.mskAG.fa /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome_mskAG/read1.sai /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//regular_unmapped_A_to_G.fq
[main] Real time: 0.020 sec; CPU: 0.002 sec
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -u         Output uncompressed data (equivalent to -l 0)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -M         Use minimiser for clustering unaligned/unplaced reads
  -K INT     Kmer size to use for minimiser [20]
  -n         Sort by read name (not compatible with samtools index command)
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
  --no-PG    do not add a PG line
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
      --write-index
               Automatically index the output files [off]
      --verbosity INT
               Set level of verbosity
sh: 0: getcwd() failed: No such file or directory
[E::hts_open_format] Failed to open file "/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome_mskAG/all.bam" : No such file or directory
samtools view: failed to open "/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome_mskAG/all.bam" for reading: No such file or directory
sh: 0: getcwd() failed: No such file or directory
cp: cannot stat '/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome_mskAG/./all.sam': No such file or directory
sh: 0: getcwd() failed: No such file or directory
[E::hts_open_format] Failed to open file "/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome_mskAG/all.bam" : No such file or directory
samtools view: failed to open "/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome_mskAG/all.bam" for reading: No such file or directory
sh: 0: getcwd() failed: No such file or directory
[bwa_aln] 17bp reads: max_diff = 2
[bwa_aln] 38bp reads: max_diff = 3
[bwa_aln] 64bp reads: max_diff = 4
[bwa_aln] 93bp reads: max_diff = 5
[bwa_aln] 124bp reads: max_diff = 6
[bwa_aln] 157bp reads: max_diff = 7
[bwa_aln] 190bp reads: max_diff = 8
[bwa_aln] 225bp reads: max_diff = 9
[main] Version: 0.7.17-r1188
[main] CMD: /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/bwa-0.7.17/bwa aln -t 20 /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/hg19/hg19.fa.mskTC.fa /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//regular_unmapped_A_to_G.fq
[main] Real time: 1.440 sec; CPU: 1.410 sec
sh: 0: getcwd() failed: No such file or directory
[main] Version: 0.7.17-r1188
[main] CMD: /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/bwa-0.7.17/bwa samse -n4 /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/hg19/hg19.fa.mskTC.fa /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome_mskTC/read1.sai /media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//regular_unmapped_A_to_G.fq
[main] Real time: 0.020 sec; CPU: 0.002 sec
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -u         Output uncompressed data (equivalent to -l 0)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -M         Use minimiser for clustering unaligned/unplaced reads
  -K INT     Kmer size to use for minimiser [20]
  -n         Sort by read name (not compatible with samtools index command)
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
  --no-PG    do not add a PG line
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
      --write-index
               Automatically index the output files [off]
      --verbosity INT
               Set level of verbosity
sh: 0: getcwd() failed: No such file or directory
[E::hts_open_format] Failed to open file "/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome_mskTC/all.bam" : No such file or directory
samtools view: failed to open "/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome_mskTC/all.bam" for reading: No such file or directory
sh: 0: getcwd() failed: No such file or directory
cp: cannot stat '/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome_mskTC/./all.sam': No such file or directory
sh: 0: getcwd() failed: No such file or directory
[E::hts_open_format] Failed to open file "/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome_mskTC/all.bam" : No such file or directory
samtools view: failed to open "/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp//genome_mskTC/all.bam" for reading: No such file or directory
Traceback (most recent call last):
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/envs/sprint/bin/sprint", line 11, in <module>
    load_entry_point('sprint==0.1.8', 'console_scripts', 'sprint')()
  File "build/bdist.linux-x86_64/egg/sprint/__init__.py", line 18, in main
  File "build/bdist.linux-x86_64/egg/sprint/pipeline.py", line 42, in pipeline
  File "build/bdist.linux-x86_64/egg/sprint/sprint_main.py", line 476, in main
  File "build/bdist.linux-x86_64/egg/sprint/tools_sam/recover_sam.py", line 39, in recover_sam
IOError: [Errno 2] No such file or directory: '/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E//tmp/genome_mskAG_all.sam'
(sprint) root@XAROS-WORKSTATION:/media/kokyriakidis/PRODUCTION/EDITING/SPRINT_ANALYSIS/AD/sprint_output/AD1E# 


```

**Comment by jumphone** [comment]
Please use SAMTOOLS == 1.2 & BWA == 0.7.12.

You can download binary "samtools 1.2" and "bwa 0.7.12" from: https://github.com/jumphone/SPRINT/tree/master/samtools_and_bwa

**Comment by kokyriakidis** [comment]
It works using these versions but I get a lot of these messages during runs
```
/home/kokyriakidis/anaconda3/envs/sprint/bin/samtools: /tmp/_MEI1ceDNd/libtinfo.so.5: no version information available (required by /lib/x86_64-linux-gnu/libncurses.so.5)

```

even though I have ncurses installed. But I guess it does not cause any problems. I get the final tables as expected.

Thanks for your help!
