### ISSUE TITLE
sprint main errors

### ISSUE THREAD

**Issue by porket-never-panic** [jumphone/SPRINT#41]
Hi
I have the same question with 15th issue.
The code is  "sprint main -1 1-eso_1_fastp.fq -2 1-eso_2_fastp.fq -p 32 ../refer_data/Sus_scrofa.Sscrofa11.1.dna.toplevbin/bwa /opt/software/anaconda2/bin/samtools"
Samtools version:1.2 ,and bwa version:0.7.12-r1039.

The details are as follows:
$ tail -100 nohup.out
[E::hts_open_format] Failed to open file .//tmp//genome_mskTC/all.bam
samtools view: failed to open ".//tmp//genome_mskTC/all.bam" for reading: No such file or directory
cp: cannot stat ‘.//tmp//genome_mskTC/./all.sam’: No such file or directory
[E::hts_open_format] Failed to open file .//tmp//genome_mskTC/all.bam
samtools view: failed to open ".//tmp//genome_mskTC/all.bam" for reading: No such file or directory
[bwa_aln] 17bp reads: max_diff = 2
[bwa_aln] 38bp reads: max_diff = 3
[bwa_aln] 64bp reads: max_diff = 4
[bwa_aln] 93bp reads: max_diff = 5
[bwa_aln] 124bp reads: max_diff = 6
[bwa_aln] 157bp reads: max_diff = 7
[bwa_aln] 190bp reads: max_diff = 8
[bwa_aln] 225bp reads: max_diff = 9
[main] Version: 0.7.17-r1188
[main] CMD: /opt/software/anaconda2/bin/bwa aln -t 32 ../refer_data/Sus_scrofa.Sscrofa11.1.dna.toplevel.fa.trans.fa.mskAG.fa .//tmp//genome_mskAG_unmapped.fq[main] Real time: 0.672 sec; CPU: 0.368 sec
[main] Version: 0.7.17-r1188
[main] CMD: /opt/software/anaconda2/bin/bwa samse -n4 ../refer_data/Sus_scrofa.Sscrofa11.1.dna.toplevel.fa.trans.fa.mskAG.fa .//tmp//transcript_mskAG/read1.sai .//tmp//genome_mskAG_unmapped.fq
[main] Real time: 0.165 sec; CPU: 0.083 sec
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
[E::hts_open_format] Failed to open file .//tmp//transcript_mskAG/all.bam
samtools view: failed to open ".//tmp//transcript_mskAG/all.bam" for reading: No such file or directory
cp: cannot stat ‘.//tmp//transcript_mskAG/./all.sam’: No such file or directory
[bwa_aln] 17bp reads: max_diff = 2
[bwa_aln] 38bp reads: max_diff = 3
[bwa_aln] 64bp reads: max_diff = 4
[bwa_aln] 93bp reads: max_diff = 5
[bwa_aln] 124bp reads: max_diff = 6
[bwa_aln] 157bp reads: max_diff = 7
[bwa_aln] 190bp reads: max_diff = 8
[bwa_aln] 225bp reads: max_diff = 9
[main] Version: 0.7.17-r1188
[main] CMD: /opt/software/anaconda2/bin/bwa aln -t 32 ../refer_data/Sus_scrofa.Sscrofa11.1.dna.toplevel.fa.trans.fa.mskTC.fa .//tmp//genome_mskTC_unmapped.fq[main] Real time: 0.602 sec; CPU: 0.421 sec
[main] Version: 0.7.17-r1188
[main] CMD: /opt/software/anaconda2/bin/bwa samse -n4 ../refer_data/Sus_scrofa.Sscrofa11.1.dna.toplevel.fa.trans.fa.mskTC.fa .//tmp//transcript_mskTC/read1.sai .//tmp//genome_mskTC_unmapped.fq
[main] Real time: 0.169 sec; CPU: 0.085 sec
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
[E::hts_open_format] Failed to open file .//tmp//transcript_mskTC/all.bam
samtools view: failed to open ".//tmp//transcript_mskTC/all.bam" for reading: No such file or directory
cp: cannot stat ‘.//tmp//transcript_mskTC/./all.sam’: No such file or directory

##############################################################################################

   SPRINT: SNP-free RNA editing Identification Toolkit

   http://sprint.tianlab.cn/SPRINT/

   Please contact 15110700005@fudan.edu.cn when questions arise.

##############################################################################################
preprocessing...
mapping...
Traceback (most recent call last):
  File "run.py", line 7, in <module>
  File "sprint/pipeline.py", line 42, in pipeline
  File "sprint/sprint_main.py", line 458, in main
  File "sprint/tools_sam/recover_sam.py", line 39, in recover_sam
IOError: [Errno 2] No such file or directory: './/tmp/transcript_mskAG_all.sam'
Failed to execute script run

What in tmp is ![image](https://github.com/user-attachments/assets/d0fd6d78-89cb-4b16-9630-9b6b44f13796)

**Comment by jumphone** [comment]
Please send the whole "nohup.out"  to 15110700005@fudan.edu.cn

**Comment by jumphone** [comment]
1. You can first use root to run: "ln -s /usr/lib64/libncurses.so.6.1 /usr/lib64/libncurses.so.5".
2. Or you can directly use the podman (docker) image of sprint. Demo scripts are in "/home/sprint".
Download podman image (434m with demo fastq): 
https://pan.baidu.com/s/10xScHRKq1IkeIyPnsVeCyA?pwd=jump 
passwd: jump

**Comment by porket-never-panic** [comment]
I have sent the whole "nohup.out" to 15110700005@fudan.edu.cn

**Comment by jumphone** [comment]
> I have sent the whole "nohup.out" to [15110700005@fudan.edu.cn](mailto:15110700005@fudan.edu.cn)

I have checked this nohup.out.

After log information of bwa alignment, there is a "help" information of samtools, which means samtools didn't get the correct input. 

You said that your bwa and samtools are in 0.7.12-r1039 and 1.2, respectively. However, I found a tag showing that you are using bwa in 0.7.17-r1188. In addition, the "help" information of your "samtools sort" is different from that of samtools v1.2.

The help information of your "samtools sort":

Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]

The help information of samtools 1.2:

Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -o FILE    Write final output to FILE rather than standard output
  -O FORMAT  Write output as FORMAT ('sam'/'bam'/'cram')   (either -O or
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam       -T is required)
  -@ INT     Set number of sorting and compression threads [1]

Legacy usage: samtools sort [options...] <in.bam> <out.prefix>
Options:
  -f         Use <out.prefix> as full final filename rather than prefix
  -o         Write final output to stdout rather than <out.prefix>.bam
  -l,m,n,@   Similar to corresponding options above

SPRINT is using the "Legacy usage" of samtools, but the "Legacy usage" was removed in later versions.

Best,
Feng
